#spring.application.name=Thread_safe_online

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_mydatabase
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 111111
      database: 1

server:
  port: 8080