---
--- Generated by Luanalysis
--- Created by zhuayang.
--- DateTime: 2024/4/12 20:38
---
local id = ARGV[1]

if (tonumber(redis.call("get",id)) <= 0) then
    return 0
end

redis.call("incrby", id, -1)

return 1